#!/usr/bin/env bash
# =============================================================================
# Dragon Agent — USB Edition Packager
# =============================================================================
# Creates a self-contained USB-ready package that customers can plug in and run.
#
# Usage:
#   bash scripts/make-usb.sh                    # Create USB package
#   bash scripts/make-usb.sh --with-model       # Include router model (~400MB)
#   bash scripts/make-usb.sh --output /mnt/usb  # Output to USB drive directly
#
# The package will contain:
#   - Dragon Agent source code
#   - Python virtual environment (portable)
#   - Router model (optional, ~400MB)
#   - Pre-configured config.yaml for Qwen2-1.5B API
#   - Launcher scripts (Linux/Mac/Windows)
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="$PROJECT_ROOT/build/usb-package"
WITH_MODEL=false
VERSION=$(git -C "$PROJECT_ROOT" describe --tags --always 2>/dev/null || echo "1.2.0")

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
err()   { echo -e "${RED}[✗]${NC} $1"; exit 1; }
step()  { echo -e "\n${CYAN}▶ $1${NC}"; }

for arg in "$@"; do
    case "$arg" in
        --with-model) WITH_MODEL=true ;;
        --output=*)   OUTPUT_DIR="${arg#*=}" ;;
        --help|-h)
            echo "Usage: bash scripts/make-usb.sh [--with-model] [--output=/path/to/usb]"
            echo "  --with-model   Include router model (Qwen2-1.5B, ~900MB)"
            echo "  --output=DIR   Output directory (default: build/usb-package)"
            exit 0
            ;;
    esac
done

# ── Step 1: Clean & prepare ──────────────────────────────────────────────
step "Preparing USB package directory..."
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR/models" "$OUTPUT_DIR/data"
info "Output: $OUTPUT_DIR"

# ── Step 2: Copy source ──────────────────────────────────────────────────
step "Copying Dragon Agent source..."
rsync -a --exclude '.git' --exclude '__pycache__' --exclude '*.pyc' \
      --exclude '.venv' --exclude 'build' --exclude 'node_modules' \
      --exclude 'dragon_data' --exclude '*.egg-info' \
      "$PROJECT_ROOT/" "$OUTPUT_DIR/src/"
info "Source copied"

# ── Step 3: Router Model ─────────────────────────────────────────────────
step "Router model..."
if $WITH_MODEL; then
    if [ -f "$PROJECT_ROOT/models/qwen2-1.5b-q4_k_m.gguf" ]; then
        cp "$PROJECT_ROOT/models/qwen2-1.5b-q4_k_m.gguf" "$OUTPUT_DIR/models/"
        info "Router model included (pre-existing)"
    else
        warn "Router model not found locally — downloading..."
        mkdir -p "$OUTPUT_DIR/models"
        MODEL_URL="https://huggingface.co/Qwen/Qwen2-1.5B-Instruct-GGUF/resolve/main/qwen2-1.5b-q4_k_m.gguf"
        if command -v wget &>/dev/null; then
            wget -q --show-progress -O "$OUTPUT_DIR/models/qwen2-1.5b-q4_k_m.gguf" "$MODEL_URL"
        else
            curl -#L -o "$OUTPUT_DIR/models/qwen2-1.5b-q4_k_m.gguf" "$MODEL_URL"
        fi
        info "Router model downloaded"
    fi
else
    warn "Router model excluded (use --with-model to include)"
    warn "Customer will download on first run (~400MB)"
fi

# ── Step 4: Pre-configured config.yaml ───────────────────────────────────
step "Creating pre-configured config.yaml..."
cat > "$OUTPUT_DIR/src/config.yaml" << YAML
# Dragon Agent — Pre-configured for AgileMind Engine API
# Generated by make-usb.sh v$VERSION
#
# Set your API key:
#   export AGILEMIND_API_KEY=your-key-here
#   export AGILEMIND_API_URL=https://api.agilemind.ai/v1  (optional)

provider:
  default: "agilemind"
  agilemind:
    model: "qwen2-1.5b"

router:
  model_path: "models/qwen2-1.5b-q4_k_m.gguf"
  n_threads: 4
  n_ctx: 512
  temperature: 0.1
  max_tokens: 128
  fallback_on_failure: true

server:
  host: "0.0.0.0"
  port: 8000
  log_level: "info"

dispatch:
  timeout_secs: 60
  max_retries: 2
  fallback_to_general: true

memory:
  persist_dir: "data/vectordb"
  embedding_model: "BAAI/bge-small-zh-v1.5"
  search_top_k: 5
  search_threshold: 0.5

guard:
  max_consecutive_repeats: 3
  max_loop_rounds: 2
  max_ineffective_retries: 3
  window_size: 50
  task_timeout_secs: 300

backup:
  endpoint: ""
  bucket: "dragon-backups"
  interval_hours: 6
YAML
info "Config pre-configured for Qwen2-1.5B API"

# ── Step 5: Launcher scripts ─────────────────────────────────────────────
step "Creating launcher scripts..."

# Linux/Mac launcher
cat > "$OUTPUT_DIR/run.sh" << 'RUNSH'
#!/usr/bin/env bash
# Dragon Agent — USB Launcher
# Double-click or run: bash run.sh
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

echo "🐉 Dragon Agent — Starting..."
echo ""

# Check Python
PYTHON=""
for py in python3.12 python3.11 python3; do
    if command -v "$py" &>/dev/null; then
        PYTHON="$py"
        break
    fi
done
if [ -z "$PYTHON" ]; then
    echo "❌ Python >= 3.11 required. Install: sudo apt install python3.12"
    echo "   Or visit: https://www.python.org/downloads/"
    read -rp "Press Enter to exit..."
    exit 1
fi
echo "✓ Found $PYTHON"

# Setup venv
if [ ! -d ".venv" ]; then
    echo "▶ Setting up environment (first run, ~2 min)..."
    "$PYTHON" -m venv .venv
    source .venv/bin/activate
    pip install --quiet --upgrade pip
    pip install --quiet -e src/
    echo "✓ Environment ready"
else
    source .venv/bin/activate
fi

# Check AgileMind API key
echo ""
if [ -n "${AGILEMIND_API_KEY:-}" ]; then
    echo "🐉 AgileMind API Key configured!"
else
    echo "⚠  AgileMind API Key not set"
    echo "   Get your key at https://console.agilemind.ai"
    echo "   Then: export AGILEMIND_API_KEY=your-key-here"
fi

# Launch setup on first run
if [ ! -f "$HOME/.dragon/config.yaml" ]; then
    echo ""
    echo "▶ First run — launching setup wizard..."
    python -m dragon setup --quick
fi

# Start
echo ""
echo "Starting Dragon Agent..."
python -m dragon chat
RUNSH
chmod +x "$OUTPUT_DIR/run.sh"
info "Linux/Mac launcher: run.sh"

# Windows launcher (PowerShell)
cat > "$OUTPUT_DIR/run.bat" << 'RUNBAT'
@echo off
title Dragon Agent
echo 🐉 Dragon Agent — Starting...
echo.

REM Check Python
where python >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo ❌ Python not found. Install from https://www.python.org/downloads/
    pause
    exit /b 1
)

REM Setup venv
if not exist ".venv" (
    echo ▶ Setting up environment (first run, ~2 min^)...
    python -m venv .venv
    call .venv\Scripts\activate.bat
    pip install --quiet --upgrade pip
    pip install --quiet -e src/
    echo ✓ Environment ready
) else (
    call .venv\Scripts\activate.bat
)

REM Check AgileMind
if defined AGILEMIND_API_KEY (
    echo 🐉 AgileMind API Key configured!
) else (
    echo ⚠  AgileMind API Key not set
    echo    Get your key at https://console.agilemind.ai
)

echo.
echo Starting Dragon Agent...
python -m dragon chat
pause
RUNBAT
info "Windows launcher: run.bat"

# ── Step 6: README ───────────────────────────────────────────────────────
step "Creating README..."
cat > "$OUTPUT_DIR/README.md" << 'README'
# 🐉 Dragon Agent — USB Edition v{VERSION}

## 即插即用 (Plug & Play)

### Linux / Mac
```bash
bash run.sh
```

### Windows
```
双击 run.bat
```

## 首次运行
首次运行会自动：
1. 创建 Python 虚拟环境 (~2分钟)
2. 下载路由模型 (~400MB，如需)
3. 提示配置 AgileMind API Key
4. 启动交互式对话

## 获取 API Key
访问 https://console.agilemind.ai 注册获取 API Key，然后：
```bash
export AGILEMIND_API_KEY=your-key-here
```

## 帮助
- 配置向导: `dragon setup`
- 切换模型: `dragon model`
- 系统检查: `dragon doctor`
README

# Replace version placeholder
sed -i "s/{VERSION}/v$VERSION/g" "$OUTPUT_DIR/README.md"
info "README created"

# ── Step 7: Summary ──────────────────────────────────────────────────────
step "Package created!"

SIZE=$(du -sh "$OUTPUT_DIR" | cut -f1)

echo -e "\n${GREEN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║     🐉 USB Package Ready!                    ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo "  Location: $OUTPUT_DIR"
echo "  Size:     $SIZE"
echo ""
echo "  To deploy:"
echo "    cp -r $OUTPUT_DIR/* /media/usb/"
echo ""
echo "  Customer runs:"
echo "    Linux/Mac: bash run.sh"
echo "    Windows:   双击 run.bat"
echo ""
echo "  Features:"
echo "    ✓ Auto-detect Qwen2-1.5B server"
echo "    ✓ Pre-configured config.yaml"
echo "    ✓ Auto-venv setup on first run"
echo "    ✓ Interactive setup wizard"
echo ""
if ! $WITH_MODEL; then
    echo "  ⚠  Router model NOT included (add --with-model)"
    echo "     Customer will download ~400MB on first run"
    echo ""
fi
